name: Publish output MD to github pages (Multiple)

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `test_web` branch
        uses: actions/checkout@v3
        with:
          ref: test_web
          fetch-depth: 0

      - name: Verify /out directory and contents
        run: |
          if [ -d "out" ] && [ "$(ls -A out)" ]; then
              echo "Contents in /out:"
              ls -la out/
          else
              echo "/out directory is empty or does not exist. Aborting."
              exit 1
          fi

      - name: Check for latest.md
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: out/latest.md

      - name: Convert latest.md to pages
        uses: wranders/markdown-to-pages-action@v1
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            out/latest.md
            out/index.md
            out/md/2025-01/index.md
            out/md/2025-02/index.md
            out/md/2025-03/index.md

      - uses: actions/upload-pages-artifact@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: steps.check_files.outputs.files_exists == 'true'
        id: deployment